// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SociedadesAPI.Data;

#nullable disable

namespace SociedadesAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251021031249_CracionDeTablas")]
    partial class CracionDeTablas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SociedadesAPI.Models.Sociedad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CapitalNeto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaveCasfim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Consecutivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Federacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nicap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequerimientoCapital")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SociedadNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tbl_Sociedades");
                });
#pragma warning restore 612, 618
        }
    }
}
